<Project>
    <PropertyGroup>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="AwesomeAssertions" Version="9.6.0" />
        <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
        <PackageVersion Include="CsvHelper" Version="33.1.0" />
        <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.10.0" />
        <PackageVersion Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23" />
        <PackageVersion Include="morelinq" Version="4.4.0" />
        <PackageVersion Include="Nerdbank.GitVersioning" Version="3.10.94" />
        <PackageVersion Include="xunit.v3" Version="4.0.0" />

        <!-- Transitive Pinning -->
        <!-- This will help prevent large(r) potentially breaking version bumps, and it will also -->
        <!-- allow us to benefit from potential performance improvements to newer package versions. -->
        <!-- In some cases, transitive pinning is necessary due to an unexplicable error, likely related to -->
        <!-- explicit nuget.config package mapping (which we have since relaxed with a catch-all pattern): -->
        <!-- NU1102 "Unable to find package ... with version (>= [a valid version])" -->
    </ItemGroup>
</Project>
