<Project>

    <Sdk Name="NorthSouthSystems.NET.Sdk" Version="14.0.1"/>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="System"/>
        <Using Include="System.Collections.Generic"/>
        <Using Include="System.Linq"/>
    </ItemGroup>

</Project>
